# Change these first
owner: cloudmppba # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
TZ: America/Argentina/Buenos_Aires

sites:
  - name: Recreo
    url: https://recreo.gba.gob.ar

  - name: Recreo Minio
    url: https://minio.recreopba.com.ar/public/img/logo.svg
    maxResponseTime: 5000

  - name: Recreo api graphql
    url: https://recreo.gba.gob.ar/graphql
    method: POST
    headers:
      - 'clientinformation: web'
      - 'Content-Type: application/json'
    body: '{ "query": "mutation\n{login_simple(grant_type: \"password\",\n    client_id: \"4\",\n    client_secret: \"Mi1IHFeQniWGziFfhTZrEsGDsO8bDGicBvQPKZwG\",\n    $RECREO_API_USERNAME: \"recreo.admin@yopmail.com\",\n    $RECREO_API_PASSWORD: \"admin\") \n{access_token}\n}","variables": {} }'

  - name: Recreo admin login
    url: https://recreo.gba.gob.ar/admin/login
    method: POST
    expectedStatusCodes:
      - 419

  - name: Actiba
    url: https://actiba.mp.gba.gob.ar

  - name: Guias Mineras
    url: $URL_GUIASMINERAS

  - name: Ronda de Negocios HML
    url: https://hml.rondadenegocios.mp.gba.gob.ar/api/
    method: POST
    expectedStatusCodes:
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: cloudmppba status
  introTitle: "Página de status de algunos de los sitios del Ministerio de la Producción, Ciencia y Tecnología."
  introMessage: Powered by **Upptime** open-source uptime monitor and status page, powered entirely by GitHub.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
